---
title: "Protein binder design workshop: RFdiffusion and BindCraft"
format:
  html:
    license: CC BY
    embed-resources: true
---

> This workshop was last run on 20th October, 2025 at Monash Caulfield campus, with attendees from Monash University (Clayton Campus and MIPS), The University of Melbourne (including the Bio21 Institute) and the Walter and Eliza Hall Institute.
>
> The content assumes access to the M3 HPC cluster at Monash University and can used on that platform for users with access to the 'rosetta' license group.
> If you are following along on another platform and you accept the [Rosetta non-commercial use license](https://rosettacommons.org/software/licensing-faq/), the [Apptainer wrapper commands for any system](non_m3_snippets.qmd) section can be adapted to run these examples on any system.


# Tentative schedule

| Time | Event |
|------|-------|
| 1:00 | Welcome, introduction and setup |
| 1:30 | RFdiffusion |
| 2:30 | Break |
| 2:45 | BindCraft |
| 3:45 | Break |
| 4:00 | Experimental validation |
| 4:30 | Wrap-up and discussion |
| 4:45 | End 🎉 |

----

::: {.callout-caution}

### Challenge - 3 mins - introduce yourself !

Within your table, fairly rapidly, introduce yourself:

- Name ?
- What do you do ?
- What are you watching on `<insert streaming service>` at the moment ?

:::

----

# Acknowledgements

Many thanks to Monash eResearch HPC team for providing the compute resources and associated support for this workshop.

Also, many thanks to [Twist Bioscience](https://www.twistbioscience.com/) for sponsoring the event.

The extraordinary efforts of the workshop team and helpers, especially organizers, made this workshop possible:

- Rebecca Bamert
- Jovita D’Silva
- Cyntia Taveneau
- Daniel Fox

And helpers / beta testers:

- Roland Calvert
- Daniel Fox
- James Lingford
- Anish Mulchandani

----

_Have suggested change to the content ?_ The Github repository for this workshop is: [https://github.com/Australian-Protein-Design-Initiative/binder-design-workshop](https://github.com/Australian-Protein-Design-Initiative/binder-design-workshop) - feel free to submit a pull request or issue.